language: node_js
node_js:
- '0.10'
- '0.12'
sudo: false
deploy:
  provider: npm
  email: jakob.mattsson@gmail.com
  skip_cleanup: true
  api_key:
    secure: "TzeIUEF33M3x2wLfiq1GVhA4exYyN2GZhxAQ8bBJXQO14sqLn7pHQlshBObR6GP9BVS2bIhaTF/h+Pyw1nk7uX3S3BjQrPePvsvYYaRXZUZg8SfgfYgbCNkXoFo6LPXnym/WDG6NJnYrH3yf6mSpFvYrZjse8GVSIpDE3xI3YmQ="
  on:
    tags: true
    branch: master
    repo: jakobmattsson/dinode
